// Type definitions for termkit
import { Terminal } from './document/Terminal';
import { Palette } from './Palette';
import { Rect } from './Rect';
import { ScreenBuffer } from './ScreenBuffer';
import { ScreenBufferHD } from './ScreenBufferHD';
import { TextBuffer } from './TextBuffer';
import { Vte } from './vte/Vte';
import { Element } from './document/Element';
import { Document } from './document/Document';
import { Container } from './document/Container';
import { Text } from './document/Text';
import { AnimatedText } from './document/AnimatedText';
import { Button } from './document/Button';
import { ToggleButton } from './document/ToggleButton';
import { TextBox } from './document/TextBox';
import { EditableTextBox } from './document/EditableTextBox';
import { Slider } from './document/Slider';
import { Bar } from './document/Bar';
import { LabeledInput } from './document/LabeledInput';
import { InlineInput } from './document/InlineInput';
import { InlineFileInput } from './document/InlineFileInput';
import { InlineMenu } from './document/InlineMenu';
import { Form } from './document/Form';
import { RowMenu } from './document/RowMenu';
import { ColumnMenu } from './document/ColumnMenu';
import { ColumnMenuMulti } from './document/ColumnMenuMulti';
import { ColumnMenuMixed } from './document/ColumnMenuMixed';
import { SelectList } from './document/SelectList';
import { SelectListMulti } from './document/SelectListMulti';
import { DropDownMenu } from './document/DropDownMenu';
import { TextTable } from './document/TextTable';
import { Layout } from './document/Layout';
import { Border } from './document/Border';
import { Window } from './document/Window';
import { Chroma } from 'chroma-js';

export interface Termkit {
  Terminal: Terminal;
  createTerminal: (options: any) => Terminal;
  Palette: Palette;
  Rect: Rect;
  ScreenBuffer: ScreenBuffer;
  ScreenBufferHD: ScreenBufferHD;
  TextBuffer: TextBuffer;
  Vte: Vte;
  Element: Element;
  Document: Document;
  Container: Container;
  Text: Text;
  AnimatedText: AnimatedText;
  Button: Button;
  ToggleButton: ToggleButton;
  TextBox: TextBox;
  EditableTextBox: EditableTextBox;
  Slider: Slider;
  Bar: Bar;
  LabeledInput: LabeledInput;
  InlineInput: InlineInput;
  InlineFileInput: InlineFileInput;
  InlineMenu: InlineMenu;
  Form: Form;
  RowMenu: RowMenu;
  ColumnMenu: ColumnMenu;
  ColumnMenuMulti: ColumnMenuMulti;
  ColumnMenuMixed: ColumnMenuMixed;
  SelectList: SelectList;
  SelectListMulti: SelectListMulti;
  DropDownMenu: DropDownMenu;
  TextTable: TextTable;
  Layout: Layout;
  Border: Border;
  Window: Window;
  chroma: Chroma;
  terminal: Terminal;
  realTerminal: Terminal;
}
